plugins {
    id 'java'
}

repositories {
    mavenCentral()
}

dependencies {
    // Используем последние версии
    testImplementation 'com.codeborne:selenide:7.6.1'
    testImplementation 'org.junit.jupiter:junit-jupiter:5.11.4'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
}

test {
    useJUnitPlatform()
    // Это добавит вывод в консоль, чтобы вы видели, что именно происходит во время тестов
    testLogging {
        events "passed", "skipped", "failed"
    }
}
